name: Release
run-name: Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release-Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          version-file: version.txt
          release-type: simple
          token: ${{ secrets.CRYPTOVIZ_TOKEN }}
          changelog-types: >
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring", "hidden": false },
              { "type": "build", "section": "Build System", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false },
              { "type": "ci", "section": "Continuous Integration", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "chore", "section": "Miscellaneous Chores", "hidden": false },
              { "type": "revert", "section": "Reverts", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false }
            ]
